### ISSUE TITLE
GRPC Fail in Deploy Mode Yarn

### ISSUE THREAD

**Issue by sanha** [snuspl/nemo#691]
At now, when Onyx runs in yarn environment, Grpc emits some errors like below:
```
701 SEVERE: Thread pool-2-thread-1 threw an uncaught exception.
702 java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
703         at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:94)
704         at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:572)
705         at io.grpc.internal.CensusTracingModule$TracingClientInterceptor.interceptCall(CensusTracingModule.java:330)
706         at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:104)
707         at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:551)
708         at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:113)
709         at edu.snu.onyx.runtime.common.comm.MessageServiceGrpc$MessageServiceBlockingStub.send(MessageServiceGrpc.java:201)
710         at edu.snu.onyx.runtime.common.message.grpc.GrpcMessageClient.send(GrpcMessageClient.java:77)
711         at edu.snu.onyx.runtime.common.message.grpc.GrpcMessageSender.send(GrpcMessageSender.java:28)
712         at edu.snu.onyx.runtime.common.message.grpc.GrpcMessageSender.send(GrpcMessageSender.java:12)
713         at edu.snu.onyx.runtime.master.resource.ExecutorRepresenter.sendControlMessage(ExecutorRepresenter.java:92)
714         at edu.snu.onyx.runtime.master.resource.ExecutorRepresenter.onTaskGroupScheduled(ExecutorRepresenter.java:79)
715         at edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy.onTaskGroupScheduled(RoundRobinSchedulingPolicy.java:235)
716         at edu.snu.onyx.runtime.master.scheduler.SchedulerRunner$SchedulerThread.run(SchedulerRunner.java:99)
717         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
718         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
719         at java.lang.Thread.run(Thread.java:748)
720 
721 Dec 08, 2017 4:27:03 AM org.apache.reef.runtime.common.launch.REEFErrorHandler onNext
722 SEVERE: Uncaught exception.
723 java.lang.Exception: Thread pool-2-thread-1 threw an uncaught exception.
724         at org.apache.reef.runtime.common.launch.REEFUncaughtExceptionHandler.uncaughtException(REEFUncaughtExceptionHandler.java:68)
725         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
726         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
727         at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
728 Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
729         at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:94)
730         at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:572)
731         at io.grpc.internal.CensusTracingModule$TracingClientInterceptor.interceptCall(CensusTracingModule.java:330)
732         at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:104)
733         at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:551)
734         at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:113)
735         at edu.snu.onyx.runtime.common.comm.MessageServiceGrpc$MessageServiceBlockingStub.send(MessageServiceGrpc.java:201)
736         at edu.snu.onyx.runtime.common.message.grpc.GrpcMessageClient.send(GrpcMessageClient.java:77)
737         at edu.snu.onyx.runtime.common.message.grpc.GrpcMessageSender.send(GrpcMessageSender.java:28)
738         at edu.snu.onyx.runtime.common.message.grpc.GrpcMessageSender.send(GrpcMessageSender.java:12)
739         at edu.snu.onyx.runtime.master.resource.ExecutorRepresenter.sendControlMessage(ExecutorRepresenter.java:92)
740         at edu.snu.onyx.runtime.master.resource.ExecutorRepresenter.onTaskGroupScheduled(ExecutorRepresenter.java:79)
741         at edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy.onTaskGroupScheduled(RoundRobinSchedulingPolicy.java:235)
742         at edu.snu.onyx.runtime.master.scheduler.SchedulerRunner$SchedulerThread.run(SchedulerRunner.java:99)
743         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
744         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
745         at java.lang.Thread.run(Thread.java:748)
```

It seems that the version of guava used by GRPC is not matched with reef-yarn.

**Comment by bgchun** [comment]
@gwsshs22 Can you take a look?

**Comment by gwkim-toss** [comment]
@bgchun `java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor` came from a bug what I fixed [REEF-1959](https://issues.apache.org/jira/browse/REEF-1959) . After the patch was merged and the new reef snapshot build was installed, the exception was disappeared . But there is another exception with the new version, 
```
Caused by: java.util.concurrent.RejectedExecutionException: Task edu.snu.onyx.runtime.master.RuntimeMaster$$Lambda$160/235359609@1d576245 rejected from java.util.concurrent.ThreadPoolExecutor@13908f9f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 32]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
        at edu.snu.onyx.runtime.master.RuntimeMaster.onContainerAllocated(RuntimeMaster.java:195)
        at edu.snu.onyx.driver.OnyxDriver$AllocatedEvaluatorHandler.onNext(OnyxDriver.java:133)
        at edu.snu.onyx.driver.OnyxDriver$AllocatedEvaluatorHandler.onNext(OnyxDriver.java:128)
        at org.apache.reef.runtime.common.utils.BroadCastEventHandler.onNext(BroadCastEventHandler.java:40)
        at org.apache.reef.util.ExceptionHandlingEventHandler.onNext(ExceptionHandlingEventHandler.java:46)
        at org.apache.reef.runtime.common.utils.DispatchingEStage$1.onNext(DispatchingEStage.java:72)
        at org.apache.reef.runtime.common.utils.DispatchingEStage$1.onNext(DispatchingEStage.java:69)
        at org.apache.reef.wake.impl.ThreadPoolStage$1.run(ThreadPoolStage.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
so we have investigated the root cause of the above exception.

**Comment by gwsshs22** [comment]
@bgchun `java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor` came from a bug what I fixed REEF-1959 . After the patch was merged and the new reef snapshot build was installed, the exception was disappeared . But there is another exception with the new version,
```
Caused by: java.util.concurrent.RejectedExecutionException: Task edu.snu.onyx.runtime.master.RuntimeMaster$$Lambda$160/235359609@1d576245 rejected from java.util.concurrent.ThreadPoolExecutor@13908f9f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 32]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
        at edu.snu.onyx.runtime.master.RuntimeMaster.onContainerAllocated(RuntimeMaster.java:195)
        at edu.snu.onyx.driver.OnyxDriver$AllocatedEvaluatorHandler.onNext(OnyxDriver.java:133)
        at edu.snu.onyx.driver.OnyxDriver$AllocatedEvaluatorHandler.onNext(OnyxDriver.java:128)
        at org.apache.reef.runtime.common.utils.BroadCastEventHandler.onNext(BroadCastEventHandler.java:40)
        at org.apache.reef.util.ExceptionHandlingEventHandler.onNext(ExceptionHandlingEventHandler.java:46)
        at org.apache.reef.runtime.common.utils.DispatchingEStage$1.onNext(DispatchingEStage.java:72)
        at org.apache.reef.runtime.common.utils.DispatchingEStage$1.onNext(DispatchingEStage.java:69)
        at org.apache.reef.wake.impl.ThreadPoolStage$1.run(ThreadPoolStage.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
so we have investigated the root cause of the above exception.

**Comment by sanha** [comment]
Moved to [JIRA](https://issues.apache.org/jira/projects/NEMO/issues/NEMO-5?filter=allopenissues)
